// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as Greeting$ReasonreTemplate from "./Greeting.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(Greeting$ReasonreTemplate.make, {
          name: "John"
        }), "root");

export {
  
}
/*  Not a pure module */
